.\" Copyright (c) 2020 Clément Dommerc <clement.dommerc@gmail.com>
.\" MIT License
.\"
.TH "QLSTATUS" "1" "2021\-04\-18" "qlstatus VERSION" "ql-status Manual"
.SH NAME
\fBqlstatus\fP \- a light and modular status bar
.SH SYNOPSIS
.SY qlstatus
.OP \-h
.OP \-v
.OP \-c file
.YS
.SH DESCRIPTION
.PP
\fBqlstatus\fP is a small program with minimalistic and modular approach
that generates system monitoring output for status bar of tiling window managers
like \fBxmonad(1)\fP or \fBdwm(1)\fP.
.PP
When \fBqlstatus\fP starts up, it reads settings from its configuration
file, \fIqlstatus.conf\fP. See the section \fBCONFIGURATION\fP below.
.SH OPTIONS
.B \-h, \-\-help
.RS 4
Print usage statement.
.RE
.sp
.B \-v, \-\-version
.RS 4
Print version and exit.
.RE
.sp
.B \-c, \-\-config <file>
.RS 4
Load settings from specified configuration file.
.SH CONFIGURATION
.PP
\fBqlstatus\fP looks for user-configuration file in the following order:
.sp
.RS 4
(1)   file specified through \fB--config\fP option
.br
(2)   \fI~/.config/qlstatus.conf\fP
.RE
.sp
If user-configuration file is not found, it looks for system-configuration
file in \fI/etc/qlstatus.conf\fP. If no configuration file is found,
\fBqlstatus\fP then is configured with default settings.
.PP
Format of the configuration file is a list of settings of the form:
.sp
.RS 4
.EX
keyword = setting
.EE
.RE
.PP
Comment lines begin with a \(oq#\(cq. For inline comments, \(oq#\(cq must
be preceded by a white space or a tab.
.PP
\fBqlstatus\fP allows you to enable and choose which \(lqmodules\(rq to
display through the global format option. Each module is composed of
\(lqtokens\(rq which may be or not displayed through the format option
of the corresponding module. Configure global and module outputs by
specifying desired format strings. See options below.
.SS global options
.TP 4
.B format
Specify global output format. It may contain the following character
sequences to enable and display desired modules. Any other character will
be print.
.sp
.in +4n
.TS
tab(;);
l l.
%D;date and time
%U;CPU usage
%F;CPU frequency
%T;temperature
%S;mounted filesystem usage
%M;memory usage
%L;brightness level
%V;audio volume
%B;battery level and status
%W;wireless SSID and signal strength
.TE
.in -4n
.sp
All modules are enabled by default.
.TP 4
.B rate
Specify refresh rate of the output in seconds or milliseconds.
Must match pattern [n]s or [n]ms.
.sp
Default: 1s
.TP 4
.B enable_spectrwm_colors
Enable or disable the support of spectrwm colors. Should be enable only
with spectrwm as window manager. Must be 0 or 1.
.sp
Default: 0
.TP 4
.B critical_color_index
Specify index of spectrwm color to use for display modules in critical
state. Must be a number in range 0 to 9.
.sp
Default: 1
.SS date and time
.TP 4
.B time_format
Specify date and time format. Must match \fBstrftime(3)\fP format
specification.
.sp
Default: %a %d %b %Y, %R %Z
.SS battery level
.TP 4
.B battery_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;current status
%V;battery level in percent
.TE
.in -4n
.sp
Default: %L %V
.TP 4
.B battery_name
Specify battery name. Must match pattern BAT[n].
.sp
Default: BAT0
.TP 4
.B battery_full_design
Enable or disable battery full design. When enabled, gives the real battery
level taking into account its wear.
Must be 0 or 1.
.sp
Default: 1
.TP 4
.B battery_label_full
Specify label to display when battery is fully charged.
.sp
Default: full
.TP 4
.B battery_label_charging
Specify label to display when battery is charging.
.sp
Default: chr
.TP 4
.B battery_label_not_charging
Specify label to display when AC is plugged but battery is not charging.
.sp
Default: chr!
.TP 4
.B battery_label_discharging
Specify label to display when battery is discharging.
.sp
Default: bat
.TP 4
.B battery_label_unknown
Specify label to display when current battery status is unknown.
.sp
Default: unk
.TP 4
.B battery_critical
Specify critical battery level in percent.
.sp
Default: 20
.SS power notifications
.TP 4
.B power_notifications
Enable or disable power notifications related to battery events.
Must be 0 or 1.
.sp
Default: 1
.TP 4
.B power_notify_icon_full
Specify icon name or icon path to use in notification triggered when
battery is fully charged.
.sp
Default: battery-full-charged
.TP 4
.B power_notify_icon_plugged
Specify icon name or icon path to use in notification triggered when
AC adapter is plugged.
.sp
Default: ac-adapter
.TP 4
.B power_notify_icon_low
Specify icon name or icon path to use in notification triggered when
battery reach the critical level.
.sp
Default: battery-caution
.SS CPU usage
.TP 4
.B cpu_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%V;CPU usage in percent
.TE
.in -4n
.sp
Default: %L %V
.TP 4
.B cpu_label
Specify the module label.
.sp
Default: cpu
.TP 4
.B cpu_critical
Specify critical CPU usage threshold in percent.
.sp
Default: 80
.SS CPU frequency
.TP 4
.B cpu_freq_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%V;CPU frequency
%U;unit
.TE
.in -4n
.sp
Default: %L %V%U
.TP 4
.B cpu_freq_label
Specify the module label.
.sp
Default: freq
.TP 4
.B cpu_freq_unit
Specify the frequency unit. Must be KHz, MHz, GHz or smart. smart
automatically scales frequency value to the shortest three digit unit.
.sp
Default: MHz
.TP 4
.B cpu_freq_scaling
If enabled, \fBqlstatus\fP looks for read scaling attributes to compute
current CPU frequency. Some scaling drivers (e.g. intel_pstate) attempt
to provide information more precisely reflecting the current CPU frequency
through these attributes. Must be 0 or 1.
.sp
Default: 1
.SS temperature
.TP 4
.B temperature_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%V;temperature in degree Celsius
.TE
.in -4n
.sp
Default: %L %V
.TP 4
.B temperature_label
Specify the module label.
.sp
Default: temp
.TP 4
.B temperature_dir
Specify path for temperature attributes directory. May contain an asterisk
\(oq*\(cq to resolve last directory of the path. If an asterisk is present
then first directory found is chosen.
.sp
Default: /sys/devices/platform/coretemp.0/hwmon/*
.TP 4
.B temperature_input
Specify an attribute number or a range to compute a temperature average.
\fBqlstatus\fP looks for attribute filenames that match pattern
temp[r]_input where r is the specified value. Value must match pattern
[n] for specific attribute file or [n]-[n] for a range of attribute files.
.sp
Default: 2-5
.TP 4
.B temperature_critical
Specify critical temperature in degree Celsius.
.sp
Default: 80
.SS mounted filesystem usage
.TP 4
.B filesystem_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%C;used space
%T;filesystem size
%F;free space
%P;used space in percent
.TE
.in -4n
.sp
Used space, free space and filesystem size are displayed in human readable way. Default: %L %C/%T %F (%P)
.TP 4
.B filesystem_label
Specify the module label.
.sp
Default: disk
.TP 4
.B filesystem_path
Specify the path of the mounted filesystem.
.sp
Default: /
.TP 4
.B filesystem_critical
Specify the critical used space threshold in percent.
.sp
Default: 90
.TP 4
.B filesystem_real_free
If enabled, display the real free space otherwise display the free space for unprivileged users.
.sp
Default: 0
.SS memory usage
.TP 4
.B memory_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%C;used memory
%T;total available memory
%U;unit
%P;used memory in percent
.TE
.in -4n
.sp
Default: %L %C/%T%U (%P)
.TP 4
.B memory_label
Specify the module label.
.sp
Default: mem
.TP 4
.B memory_unit
Specify the memory unit. Must be KiB, MiB, GiB or smart. smart
automatically scales used and total memory value to the shortest three
digit unit.
.sp
Default: MiB
.TP 4
.B memory_critical
Specify critical memory usage threshold in percent.
.sp
Default: 80
.SS brightness level
.TP 4
.B brightness_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%V;brightness level in percent
.TE
.in -4n
.sp
Default: %L %V
.TP 4
.B brightness_label
Specify the module label.
.sp
Default: brg
.TP 4
.B brightness_dir
Specify path for backlight attributes directory. Should not be changed.
.sp
Default: /sys/class/backlight/intel_backlight
.SS audio volume
.TP 4
.B volume_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;label
%V;volume level in percent
.TE
.in -4n
.sp
Default: %L %V
.TP 4
.B volume_label
Specify the module label.
.sp
Default: vol
.TP 4
.B volume_muted_label
Specify the label when audio is muted.
.sp
Default: mut
.TP 4
.B volume_sink_name
Specify sink name. See \fBpactl(1)\fP for how to get information about
sinks.
.sp
Default: alsa_output.pci-0000_00_1f.3.analog-stereo
.SS wireless SSID and signal
.TP 4
.B wireless_format
Specify module format. It may contain the following character sequences:
.sp
.in +4n
.TS
tab(;);
l l.
%L;current SSID
%V;signal strength in percent
.TE
.in -4n
.sp
Default: %L: %V
.TP 4
.B wireless_unknown_label
Specify the label when SSID is unknown.
.sp
Default: SSID unk
.TP 4
.B wireless_interface
Specify name of wireless interface.
.sp
Default: wlan0
.SH INTEGRATION IN XMOBAR
.PP
In your \fBxmobar\fP configuration file, you must add the \fBCommandReader\fP plugin in the
\fBcommands\fP option and specify \fBqlstatus\fP as the given program to display its standard output:
.sp
.RS 4
.EX
Config { ...
       , commands = [ Run CommandReader "qlstatus" "status"
                    , Run XMonadLog
                    ]
       , template = "%XMonadLog% }{ %status% "
}
.EE
.SH INTEGRATION IN DWM
.PP
dwm reads the name of the root window and redirects it to its statusbar
area. The root window is the root of the window tree handled by the window
manager. Like any other window, the root window has a name, but it is
usually undefined because the root window always runs in the background.
.PP
You can compile following C program to redirect \fBqlstatus\fP output as
the name of the root window:
.sp
.RS 4
.EX
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <X11/Xlib.h>

int             main(int argc, char *argv[]) {
    Display     *dpy = NULL;
    Window      win = 0;
    size_t      length = 0;
    ssize_t     bytes_read = 0;
    char        *input = NULL;

    dpy = XOpenDisplay(getenv("DISPLAY"));
    if (dpy == NULL) {
        fprintf(stderr, "Can't open display, exiting.\\n");
        exit(EXIT_FAILURE);
    }

    win = DefaultRootWindow(dpy);
    while ((bytes_read = getline(&input, &length, stdin)) != EOF) {
        input[strlen(input) - 1] = 0;
        XStoreName(dpy, win, input);
        XFlush(dpy);
    }
    free(input);
    return 0;
}
.EE
.RE
.PP
Save this code in \fIdwm-setstatus.c\fP and compile it:
.sp
.RS 4
.EX
gcc dwm-setstatus.c -lX11 -o dwm-setstatus
.EE
.RE
.PP
Finally, move or add \fBdwm-setstatus\fP binary to your $PATH. To use
\fBqlstatus\fP as dwm statusbar, you can for example add into
\fI~/.xinitrc\fP:
.sp
.RS 4
.EX
\&...

(qlstatus | dwm-setstatus) &
exec dwm
.EE
.SH INTEGRATION IN SPECTRWM
.PP
Specify \fBqlstatus\fP as external script through the option
\fBbar_action\fP in your spectrwm configuration file:
.sp
.RS 4
.EX
bar_action = qlstatus
.EE
.RE
.PP
That's it.
.SH FILES
.I /etc/qlstatus.conf
.br
.I /usr/local/bin/qlstatus
.br
.I /usr/local/share/man/man1/qlstatus.1
.SH NOTES
The support of spectrwm colors is stopped for now.
.SH BUGS
In case of bug, please open an issue on
.UR https://\:github.com/\:qlem/\:qlstatus
GitHub repository page
.UE .
.SH SEE ALSO
.BR dwm (1),
.BR spectrwm (1)
.SH AUTHORS
\fBqlstatus\fP was written and currently maintained by Clément Dommerc.
